apiVersion: v1
kind: Namespace
metadata:
  name: bibliophage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-standard-user
  namespace: bibliophage
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/bibliophage/db-standard-user
      property: username
    secretKey: username
  - remoteRef:
      key: kv/nekropolis/bibliophage/db-standard-user
      property: password
    secretKey: password
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: db-standard-user
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-superuser
  namespace: bibliophage
spec:
  data:
  - remoteRef:
      key: kv/nekropolis/bibliophage/db-standard-user
      property: username
    secretKey: username
  - remoteRef:
      key: kv/nekropolis/bibliophage/db-standard-user
      property: password
    secretKey: password
  refreshInterval: 1h0m0s
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: db-superuser
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bibliophage-vectors
  namespace: bibliophage
spec:
  bootstrap:
    initdb:
      database: vectors
      owner: bibliophage
      secret:
        name: db-standard-user
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 17
    name: postgresql-standard-trixie
  instances: 3
  managed:
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            annotations:
              kube-vip.io/loadbalancerIPs: 192.168.14.6
            name: bibliophage-vectors-db-rw
          spec:
            type: LoadBalancer
  storage:
    size: 10Gi
  superuserSecret:
    name: db-superuser
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bibliophage-vectors
  namespace: bibliophage
spec:
  cluster:
    name: bibliophage-vectors
  extensions:
  - ensure: present
    name: vector
  name: vectors
  owner: bibliophage
