apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bibliophage-vectors
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 17
  instances: 3
  superuserSecret:
    name: bibliophage-superuser
  bootstrap:
    initdb:
      database: vectors
      owner: bibliophage
      secret:
        name: bibliophage-app-user
  storage:
    size: 10Gi
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "bibliophage-vectors-db-rw"
              annotations:
                kube-vip.io/loadbalancerIPs: 192.168.249.6
            spec:
              type: LoadBalancer
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bibliophage-vectors
spec:
  name: vectors
  owner: bibliophage
  cluster:
    name: bibliophage-vectors
  extensions:
  - name: vector
    ensure: present
