apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  labels:
    app.kubernetes.io/name: ferretdb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bibliophage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ferretdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ferretdb
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: bibliophage
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.1.0
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: ferretdb
                  key: connectionstring
            - name: FERRETDB_TELEMETRY
              value: disable
