apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.14.8
  labels:
  name: ferretdb
spec:
  ports:
  - name: main
    port: 27017
    protocol: TCP
    targetPort: 27017
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/name: ferretdb
  type: LoadBalancer
